# Generated by Django 5.1.2 on 2025-04-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
