# Generated by Django 5.2 on 2025-05-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0005_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='idea_principal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
