# Generated by Django 5.2 on 2025-05-01 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0007_ideausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ideausuario',
            name='me_gusta',
            field=models.ManyToManyField(blank=True, related_name='me_gusta_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
